stages:
  - build
  - deploy_compose

build:prod:
  stage: build
  script:
    - sh .gitlab-ci/docker_build.sh
  only:
    - main
  tags:
    - shell-runner

deploy:prod:
  stage: deploy_compose
  environment:
    name: prod
  script:
    - sh .gitlab-ci/docker_deploy.sh
  variables:
    ENV: prod
    APP: leadershack2022-anomaly-detector
  when: manual
  only:
    - main
  tags:
    - shell-runner

build:test:
  stage: build
  script:
    - sh .gitlab-ci/docker_build_test.sh
  only:
    - test
  tags:
    - shell-runner

deploy:test:
  stage: deploy_compose
  environment:
    name: test
  script:
    - sh .gitlab-ci/docker_deploy_test.sh
  variables:
    ENV: test
    APP: leadershack2022-anomaly-detector-test
  when: manual
  only:
    - test
  tags:
    - shell-runner
